meta_product_name: "Bonded"
meta_title: "Bonded- Product tagline"
meta_description: "Bonded provides access to a community who are there to listen, share information and offer valuable advice."
meta_image: "friends-bkg.png" # should exist in `app/assets/images/`
